<?php
$prefix = $_ENV['prefix'];

$routes = [
    "{$prefix}/" => 'src/Controllers/HomeController.php',
    "{$prefix}/home" => 'src/Controllers/HomeController.php',
    "{$prefix}/login" => 'src/Controllers/Authentication/LoginController.php',
    "{$prefix}/register" => 'src/Controllers/Authentication/RegisterController.php',
    "{$prefix}/logout" => 'src/Controllers/Authentication/LogoutController.php',
    "{$prefix}/event" => 'src/Controllers/EventPageController.php',
    "{$prefix}/search" => 'src/Controllers/SearchController.php',
    "{$prefix}/contact" => 'src/Controllers/Customer/ContactFormController.php',
    "{$prefix}/customerSupport" => 'src/Controllers/Admin/CustomerSupportController.php',
    "{$prefix}/deleteSubmission" => 'src/Controllers/DeleteSubmissionController.php',
    "{$prefix}/all_events" => 'src/Controllers/Admin/AllEventsBoardController.php',
    "{$prefix}/event_addition" => 'src/Controllers/Admin/EventAdditionController.php',
    "{$prefix}/event_update" => 'src/Controllers/Admin/EventUpdateController.php',
    "{$prefix}/event_delete" => 'src/Controllers/Admin/EventDeleteController.php',
    "{$prefix}/all_users" => 'src/Controllers/Admin/AllUsersBoardController.php',
    "{$prefix}/forgotPassword" => 'src/Controllers/Authentication/ForgotPasswordController.php',
    "{$prefix}/recoverPassword" => 'src/Controllers/Authentication/RecoverPasswordController.php',
    "{$prefix}/resetPassword" => 'src/Controllers/Authentication/ResetPasswordController.php',
    "{$prefix}/verify" => 'src/Controllers/Authentication/VerifyAccountController.php',
    "{$prefix}/reserve" => 'src/Controllers/PurchaseManagement/EventReservationController.php',
    "{$prefix}/payment" => 'src/Controllers/PurchaseManagement/PaymentController.php',
    "{$prefix}/cancel" => 'src/Controllers/PurchaseManagement/CancelReservationController.php',
    "{$prefix}/view-tickets" => 'src/Controllers/Customer/TicketsPageController.php',
    "{$prefix}/ticket" => 'src/Controllers/Utility/TicketPDFController.php',
    "{$prefix}/userProfile" => 'src/Controllers/Authentication/ChangeAccountInfoController.php',
    "{$prefix}/changePassword" => 'src/Controllers/Authentication/ChangePasswordController.php',
    "{$prefix}/notifications" => 'src/Controllers/NotificationController.php',
    "{$prefix}/set_currency" => 'src/Controllers/Utility/SetCurrencyController.php',
    "{$prefix}/dashboard" => 'src/Controllers/Admin/DashboardController.php',
    "{$prefix}/all_tickets" => 'src/Controllers/Admin/AllTicketPurchasesController.php',
];
